### ISSUE TITLE
Is the client thread safe?

### ISSUE THREAD

**Issue by sillyousu** [dogenzaka/go-iap#14]
I haven't dig deep into the code. Is it thread safe?

**Comment by jun06t** [comment]
Yes, as far as I know.
The client for Google Play wraps http.Client and it is safe for concurrent use as the document says.

> Clients and Transports are safe for concurrent use by multiple goroutines and for efficiency should only be created once and re-used.

http://golang.org/pkg/net/http/

And the client for AppStore uses [gorequest](https://github.com/parnurzeal/gorequest) which is also wraps http.Client.

**Comment by sillyousu** [comment]
Thanks @jun06t.  It's a good project. But the API itself is not so good.
App Store:
>To retrieve the receipt data, use the appStoreReceiptURL method of NSBundle to locate the app’s 
receipt, and then read the entire file. If the appStoreReceiptURL method is not available, you can fall 
back to the value of a transaction's transactionReceipt property for backward compatibility. Then send 
this data to your server—as with all interactions with your server, the details are your responsibility.

The receipt is not  for one transaction but for all transactions the user has ever launched. 
The receipt size is unacceptable large (5KB per transaction). Finally I have to use  **transactionReceipt** field in **SKPaymentTransaction** which is deprecated after iOS 7.0.
https://developer.apple.com/library/ios/documentation/StoreKit/Reference/SKPaymentTransaction_Class/index.html#//apple_ref/occ/instp/SKPaymentTransaction/transactionReceipt

Google Play:
I get 404 from Google API for some valid order. I google around and found this:
>If you are selling the same INAPP product to the same user muliple times within a short period, then it's very likely that all access tokens except the last purchase will return a 404 code.

https://stackoverflow.com/questions/25401759/check-andriod-purchase-status-but-return-the-purchase-token-was-not-found/31759556#31759556

So I gave up this API :(

And then I found I can verify **purchase data** with **signature** and the **public key** from google play app console.
http://robertomurray.co.uk/blog/2013/server-side-google-play-in-app-billing-receipt-validation-and-testing/

Maybe I should bring out my code and send you a pr

**Comment by jun06t** [comment]
Thanks for your investigation about Apple and Google API.
Some of their specifications annoy me as you say :(

> Maybe I should bring out my code and send you a pr

I'm grad to hear it. I'm looking forward to your pr :)
