### ISSUE TITLE
apple store response is diffent

### ISSUE THREAD

**Issue by li76168** [dogenzaka/go-iap#25]
My response struct is :

IAPResponse struct {
		Receipt struct {
			AppItemID                 string `json:"app_item_id"`
			Bid                       string `json:"bid"`
			Bvrs                      string `json:"bvrs"`
			ItemID                    string `json:"item_id"`
			OriginalPurchaseDate      string `json:"original_purchase_date"`
			OriginalPurchaseDateMs    string `json:"original_purchase_date_ms"`
			OriginalPurchaseDatePst   string `json:"original_purchase_date_pst"`
			OriginalTransactionID     string `json:"original_transaction_id"`
			ProductID                 string `json:"product_id"`
			PurchaseDate              string `json:"purchase_date"`
			PurchaseDateMs            string `json:"purchase_date_ms"`
			PurchaseDatePst           string `json:"purchase_date_pst"`
			Quantity                  string `json:"quantity"`
			TransactionID             string `json:"transaction_id"`
			UniqueIdentifier          string `json:"unique_identifier"`
			UniqueVendorIdentifier    string `json:"unique_vendor_identifier"`
			VersionExternalIdentifier string `json:"version_external_identifier"`
		} `json:"receipt"`
		Status int `json:"status"`
	}

**Comment by jun06t** [comment]
Thanks for your report.
I would like to ask you a question. Which is your In-App Purchase product types;
- Consumable
- Non-Consumable
- Auto-Renewable Subscription
- Free Subscription
- Non-Renewing Subscription

**Comment by li76168** [comment]
It is consumable.

**Comment by zjx20** [comment]
@li76168 I guess your receipt is iOS 6 style, you should get the receipt data via `[NSData dataWithContentsOfURL:[[NSBundle mainBundle] appStoreReceiptURL]]`

**Comment by cupen** [comment]
@li76168  nothing special, I just format your code
```go
type IAPResponse struct {
	Receipt struct {
		AppItemID                 string `json:"app_item_id"`
		Bid                       string `json:"bid"`
		Bvrs                      string `json:"bvrs"`
		ItemID                    string `json:"item_id"`
		OriginalPurchaseDate      string `json:"original_purchase_date"`
		OriginalPurchaseDateMs    string `json:"original_purchase_date_ms"`
		OriginalPurchaseDatePst   string `json:"original_purchase_date_pst"`
		OriginalTransactionID     string `json:"original_transaction_id"`
		ProductID                 string `json:"product_id"`
		PurchaseDate              string `json:"purchase_date"`
		PurchaseDateMs            string `json:"purchase_date_ms"`
		PurchaseDatePst           string `json:"purchase_date_pst"`
		Quantity                  string `json:"quantity"`
		TransactionID             string `json:"transaction_id"`
		UniqueIdentifier          string `json:"unique_identifier"`
		UniqueVendorIdentifier    string `json:"unique_vendor_identifier"`
		VersionExternalIdentifier string `json:"version_external_identifier"`
	} `json:"receipt"`
	Status int `json:"status"`
}
```
