### ISSUE TITLE
iTunes API returns 200

### ISSUE THREAD

**Issue by mhemmings** [dogenzaka/go-iap#26]
On an error, iTunes API returns a 200 because it's terrible.

This means that this line is redundant:
https://github.com/dogenzaka/go-iap/blob/master/appstore/validator.go#L113

How should we progress forward with errors? Parse the status inside the library?

**Comment by jun06t** [comment]
@mhemmings 
Thanks for your report.
I don't want to change interface of this function, so I'll only remove this line.
