### ISSUE TITLE
Go get not working 

### ISSUE THREAD

**Issue by pjebs** [dogenzaka/go-iap#31]
Due to this: https://github.com/golang/oauth2/issues/201

**Comment by jun06t** [comment]
i guess your oauth2 repository is put in detached HEAD.
please run the following command as error message says.
```
$ cd /Developer/Projects/GOPATH/src/golang.org/x/oauth2
$ git checkout master
```
Have you used ``godep restore`` before? ``godep restore`` disables you from updating branch by ``go get -u``
https://github.com/tools/godep/issues/453
