### ISSUE TITLE
Getting empty response body from Verify

### ISSUE THREAD

**Issue by mhemmings** [dogenzaka/go-iap#32]
Calling `appstore.Verify` is giving me EOF errors. On closer inspection, these are being thrown by https://github.com/dogenzaka/go-iap/blob/e9d5da1f8f6bff09e3f0ff777a44fe617e45ae52/appstore/validator.go#L112 as the body from the previous request is empty.

Inspecting the gorequest with `AsCurlCommand()` and running that as a curl command, the request succeeds with a valid (albeit large) response body every time.

Ultimately, what appears to be happening is when the receipt response is large (this can happen _very_ quickly with iOS especially with autorenewing subscriptions) something isn't reading it properly. I don't know if this is in the std lib or gorequest, all I know is the string being passed to the json decoder is empty, and it's never empty when the same request is ran with curl.

**Comment by mhemmings** [comment]
It looks like the bug is with the gorequest library.
When I remove it and replace it with standard library code, everything works perfectly
```
// Verify sends receipts and gets validation result
func (c *Client) Verify(req IAPRequest, result interface{}) error {
	b := new(bytes.Buffer)
	json.NewEncoder(b).Encode(req)

	request, _ := http.NewRequest("POST", c.URL, b)

	resp, err := http.DefaultClient.Do(request)
	defer resp.Body.Close()

	if err != nil {
		return err
	}

	err = json.NewDecoder(resp.Body).Decode(result)

	return err
}
```
I can't tell from looking at the docs for gorequest if this is their bug, or wrong implementation in this library?

**Comment by jun06t** [comment]
thanks for your report :-)
i've fixed it to use http package instead of gorequest.
